services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    volumes:
      - .:/CodingChallenge

# db: <--- elimínalo si no lo usarás
#   image: mysql:8.0
#   environment:
#     MYSQL_DATABASE: flaskdb
#     MYSQL_USER: flaskuser
#     MYSQL_PASSWORD: flaskpass
#     MYSQL_ROOT_PASSWORD: rootpass
#   ports:
#     - "3306:3306"
#   volumes:
#     - mysql_data:/var/lib/mysql

# volumes:
#   mysql_data:
